import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GlobalContextProvider } from "./_context/Global";
import { Navigation } from "./_components/Navigation";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalContextProvider>
          {children}
          <Navigation />
        </GlobalContextProvider>
      </body>
    </html>
  );
}
